image: Visual Studio 2017
version: 4.0.0-alpha-{build}
configuration: Release
environment:
  ZendeskApi_Credentials_Url:
    secure: EqmTftam7aCYhmq7iHOoogNjL1vPuxrBSMVGmTY5WdI8GjTFeTtX8ayBLuWCyj4e
  ZendeskApi_Credentials_Username: 
    secure: whZ6DOkeg5NgmNdWKmiQnd0XBziOlelSNKmmWpHmEoZWD3uB4wE9GB0DXso/kuNu
  ZendeskApi_Credentials_Token: 
    secure: yDdhxnlW5TvBOM4GilXQkiwTqWyr3jxuO6ht1edFz5BILYwp4z/fkasYcOfibMCt
before_build:
  - dotnet restore
build:
  project: ZendeskApiClient.sln
  parallel: true
  verbosity: minimal
clone_depth: 1
test_script:
- dotnet test -c Release .\test\ZendeskApi.Client.Tests\ZendeskApi.Client.Tests.csproj
after_build:
- dotnet pack .\src\ZendeskApi.Client\ZendeskApi.Client.csproj -o ../../output --no-build
artifacts:
- path: 'output\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: ZkYI4stkqiH2+3Y5u4kv6/WEbVpiyoQSSXp5is3ODPxlYu1uMdnkK1dDgfTSH4VG
  artifact: /.*nupkg/
  on:
    APPVEYOR_REPO_TAG: true
for:
-
  branches:
    only:
      - master
  test_script:
    - dotnet test -c Release .\test\ZendeskApi.Client.IntegrationTests\ZendeskApi.Client.IntegrationTests.csproj
