image: Visual Studio 2017
version: 3.0.0-beta-{build}
configuration: Release
before_build:
  - dotnet restore
build:
  project: ZendeskApiClient.sln
  parallel: true
  verbosity: minimal
clone_depth: 1
test_script:
- dotnet test -c Release .\test\ZendeskApi.Client.Tests\ZendeskApi.Client.Tests.csproj
after_build:
- dotnet pack .\src\ZendeskApi.Client\ZendeskApi.Client.csproj -o ../../output --no-build
- dotnet pack .\src\ZendeskApi.Client.Abstractions\ZendeskApi.Client.Abstractions.csproj -o ../../output --no-build
artifacts:
- path: 'output\*.nupkg'
notifications:
- provider: HipChat
  room: 'Eng :: Open Source'
  auth_token:
    secure: eJWABMRPoyfEF9iLzFaTcUEqTc7/64v0FtS1qQe4yhs=
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: false
deploy:
- provider: NuGet
  api_key:
    secure: 6MzbzEs4YdJKS67Gio5gEO8mNKmwfC4UHTCmECZ1KOutI6ndm4vAECazmVNB6an7
  artifact: /.*nupkg/
  on:
    APPVEYOR_REPO_TAG: true